// Generated from ncaa_d1_teams_espn_abbrevs_2026.xlsx
// Source: /Users/andrevlahakis/Downloads/ncaa_d1_teams_espn_abbrevs_2026.xlsx
export const ESPN_ABBREVIATIONS_2026: Record<string, string> = {
  'abilene christian': 'ACU',
  'abilene christian wildcats': 'ACU',
  'abilene chrstn': 'ACU',
  'air force': 'AF',
  'air force falcons': 'AF',
  'akron': 'AKR',
  'akron zips': 'AKR',
  'alabama': 'ALA',
  'alabama a and m': 'AAMU',
  'alabama a and m bulldogs': 'AAMU',
  'alabama crimson': 'ALA',
  'alabama crimson tide': 'ALA',
  'alabama st': 'ALST',
  'alabama state': 'ALST',
  'alabama state hornets': 'ALST',
  'alcorn st': 'ALCN',
  'alcorn state': 'ALCN',
  'alcorn state braves': 'ALCN',
  'american': 'AMER',
  'american university': 'AMER',
  'american university eagles': 'AMER',
  'app state': 'APP',
  'app state mountaineers': 'APP',
  'ar pine bluff': 'UAPB',
  'arizona': 'ARIZ',
  'arizona st': 'ASU',
  'arizona state sun': 'ASU',
  'arizona state sun devils': 'ASU',
  'arizona wildcats': 'ARIZ',
  'arkansas': 'ARK',
  'arkansas pine bluff golden': 'UAPB',
  'arkansas pine bluff golden lions': 'UAPB',
  'arkansas razorbacks': 'ARK',
  'arkansas st': 'ARST',
  'arkansas state red': 'ARST',
  'arkansas state red wolves': 'ARST',
  'army': 'ARMY',
  'army black': 'ARMY',
  'army black knights': 'ARMY',
  'auburn': 'AUB',
  'auburn tigers': 'AUB',
  'austin peay': 'APSU',
  'austin peay governors': 'APSU',
  'bakersfield': 'CSUB',
  'ball state': 'BALL',
  'ball state cardinals': 'BALL',
  'baylor': 'BAY',
  'baylor bears': 'BAY',
  'bellarmine': 'BELL',
  'bellarmine knights': 'BELL',
  'belmont': 'BEL',
  'belmont bruins': 'BEL',
  'bethune': 'BCU',
  'bethune cookman': 'BCU',
  'bethune cookman wildcats': 'BCU',
  'binghamton': 'BING',
  'binghamton bearcats': 'BING',
  'boise st': 'BOIS',
  'boise state': 'BOIS',
  'boise state broncos': 'BOIS',
  'boston college': 'BC',
  'boston college eagles': 'BC',
  'boston u': 'BU',
  'boston university': 'BU',
  'boston university terriers': 'BU',
  'bowling green': 'BGSU',
  'bowling green falcons': 'BGSU',
  'bradley': 'BRAD',
  'bradley braves': 'BRAD',
  'brown': 'BRWN',
  'brown bears': 'BRWN',
  'bryant': 'BRY',
  'bryant bulldogs': 'BRY',
  'bucknell': 'BUCK',
  'bucknell bison': 'BUCK',
  'buffalo': 'BUF',
  'buffalo bulls': 'BUF',
  'butler': 'BUT',
  'butler bulldogs': 'BUT',
  'byu': 'BYU',
  'byu cougars': 'BYU',
  'c arkansas': 'CARK',
  'c connecticut': 'CCSU',
  'c michigan': 'CMU',
  'ca baptist': 'CBU',
  'cal poly': 'CP',
  'cal poly mustangs': 'CP',
  'cal state bakersfield': 'CSUB',
  'cal state bakersfield roadrunners': 'CSUB',
  'cal state fullerton': 'CSUF',
  'cal state fullerton titans': 'CSUF',
  'cal state northridge': 'CSUN',
  'cal state northridge matadors': 'CSUN',
  'california': 'CAL',
  'california baptist': 'CBU',
  'california baptist lancers': 'CBU',
  'california golden': 'CAL',
  'california golden bears': 'CAL',
  'campbell': 'CAM',
  'campbell fighting': 'CAM',
  'campbell fighting camels': 'CAM',
  'canisius': 'CAN',
  'canisius golden': 'CAN',
  'canisius golden griffins': 'CAN',
  'central arkansas': 'CARK',
  'central arkansas bears': 'CARK',
  'central connecticut blue': 'CCSU',
  'central connecticut blue devils': 'CCSU',
  'central michigan': 'CMU',
  'central michigan chippewas': 'CMU',
  'charleston': 'COFC',
  'charleston cougars': 'COFC',
  'charleston so': 'CHSO',
  'charleston southern': 'CHSO',
  'charleston southern buccaneers': 'CHSO',
  'charlotte': 'CLT',
  'charlotte 49ers': 'CLT',
  'chattanooga': 'UTC',
  'chattanooga mocs': 'UTC',
  'chicago st': 'CHST',
  'chicago state': 'CHST',
  'chicago state cougars': 'CHST',
  'cincinnati': 'CIN',
  'cincinnati bearcats': 'CIN',
  'clemson': 'CLEM',
  'clemson tigers': 'CLEM',
  'cleveland st': 'CLE',
  'cleveland state': 'CLE',
  'cleveland state vikings': 'CLE',
  'coastal': 'CCU',
  'coastal carolina': 'CCU',
  'coastal carolina chanticleers': 'CCU',
  'colgate': 'COLG',
  'colgate raiders': 'COLG',
  'colorado': 'COLO',
  'colorado buffaloes': 'COLO',
  'colorado st': 'CSU',
  'colorado state': 'CSU',
  'colorado state rams': 'CSU',
  'columbia': 'COLU',
  'columbia lions': 'COLU',
  'coppin st': 'COPP',
  'coppin state': 'COPP',
  'coppin state eagles': 'COPP',
  'cornell': 'COR',
  'cornell big': 'COR',
  'cornell big red': 'COR',
  'creighton': 'CREI',
  'creighton bluejays': 'CREI',
  'csu northridge': 'CSUN',
  'dartmouth': 'DART',
  'dartmouth big': 'DART',
  'dartmouth big green': 'DART',
  'davidson': 'DAV',
  'davidson wildcats': 'DAV',
  'dayton': 'DAY',
  'dayton flyers': 'DAY',
  'delaware': 'DEL',
  'delaware blue': 'DEL',
  'delaware blue hens': 'DEL',
  'delaware st': 'DSU',
  'delaware state': 'DSU',
  'delaware state hornets': 'DSU',
  'denver': 'DEN',
  'denver pioneers': 'DEN',
  'depaul': 'DEP',
  'depaul blue': 'DEP',
  'depaul blue demons': 'DEP',
  'detroit mercy': 'DETM',
  'detroit mercy titans': 'DETM',
  'drake': 'DRKE',
  'drake bulldogs': 'DRKE',
  'drexel': 'DREX',
  'drexel dragons': 'DREX',
  'duke': 'DUKE',
  'duke blue': 'DUKE',
  'duke blue devils': 'DUKE',
  'duquesne': 'DUQ',
  'duquesne dukes': 'DUQ',
  'e illinois': 'EIU',
  'e kentucky': 'EKU',
  'e michigan': 'EMU',
  'e texas a and m': 'ETAM',
  'e washington': 'EWU',
  'east carolina': 'ECU',
  'east carolina pirates': 'ECU',
  'east tennessee state': 'ETSU',
  'east tennessee state buccaneers': 'ETSU',
  'east texas a and m': 'ETAM',
  'east texas a and m lions': 'ETAM',
  'eastern illinois': 'EIU',
  'eastern illinois panthers': 'EIU',
  'eastern kentucky': 'EKU',
  'eastern kentucky colonels': 'EKU',
  'eastern michigan': 'EMU',
  'eastern michigan eagles': 'EMU',
  'eastern washington': 'EWU',
  'eastern washington eagles': 'EWU',
  'elon': 'ELON',
  'elon phoenix': 'ELON',
  'etsu': 'ETSU',
  'evansville': 'EVAN',
  'evansville purple': 'EVAN',
  'evansville purple aces': 'EVAN',
  'fairfield': 'FAIR',
  'fairfield stags': 'FAIR',
  'fairleigh dickinson': 'FDU',
  'fairleigh dickinson knights': 'FDU',
  'fau': 'FAU',
  'fdu': 'FDU',
  'fgcu': 'FGCU',
  'fiu': 'FIU',
  'florida': 'FLA',
  'florida a and m': 'FAMU',
  'florida a and m rattlers': 'FAMU',
  'florida atlantic': 'FAU',
  'florida atlantic owls': 'FAU',
  'florida gators': 'FLA',
  'florida gulf coast': 'FGCU',
  'florida gulf coast eagles': 'FGCU',
  'florida international': 'FIU',
  'florida international panthers': 'FIU',
  'florida st': 'FSU',
  'florida state': 'FSU',
  'florida state seminoles': 'FSU',
  'fordham': 'FOR',
  'fordham rams': 'FOR',
  'fresno st': 'FRES',
  'fresno state': 'FRES',
  'fresno state bulldogs': 'FRES',
  'fullerton': 'CSUF',
  'furman': 'FUR',
  'furman paladins': 'FUR',
  'g washington': 'GW',
  'ga southern': 'GASO',
  'gardner webb': 'GWEB',
  'gardner webb runnin\'': 'GWEB',
  'gardner webb runnin\' bulldogs': 'GWEB',
  'george mason': 'GMU',
  'george mason patriots': 'GMU',
  'george washington': 'GW',
  'george washington revolutionaries': 'GW',
  'georgetown': 'GTWN',
  'georgetown hoyas': 'GTWN',
  'georgia': 'UGA',
  'georgia bulldogs': 'UGA',
  'georgia southern': 'GASO',
  'georgia southern eagles': 'GASO',
  'georgia st': 'GAST',
  'georgia state': 'GAST',
  'georgia state panthers': 'GAST',
  'georgia tech': 'GT',
  'georgia tech yellow': 'GT',
  'georgia tech yellow jackets': 'GT',
  'gonzaga': 'GONZ',
  'gonzaga bulldogs': 'GONZ',
  'grambling': 'GRAM',
  'grambling tigers': 'GRAM',
  'grand canyon': 'GCU',
  'grand canyon lopes': 'GCU',
  'green bay': 'GB',
  'green bay phoenix': 'GB',
  'hampton': 'HAMP',
  'hampton pirates': 'HAMP',
  'harvard': 'HARV',
  'harvard crimson': 'HARV',
  'hawai\'i': 'HAW',
  'hawai\'i rainbow': 'HAW',
  'hawai\'i rainbow warriors': 'HAW',
  'high point': 'HPU',
  'high point panthers': 'HPU',
  'hofstra': 'HOF',
  'hofstra pride': 'HOF',
  'holy cross': 'HC',
  'holy cross crusaders': 'HC',
  'hou christian': 'HCU',
  'houston': 'HOU',
  'houston christian': 'HCU',
  'houston christian huskies': 'HCU',
  'houston cougars': 'HOU',
  'howard': 'HOW',
  'howard bison': 'HOW',
  'idaho': 'IDHO',
  'idaho st': 'IDST',
  'idaho state': 'IDST',
  'idaho state bengals': 'IDST',
  'idaho vandals': 'IDHO',
  'illinois': 'ILL',
  'illinois fighting': 'ILL',
  'illinois fighting illini': 'ILL',
  'illinois st': 'ILST',
  'illinois state': 'ILST',
  'illinois state redbirds': 'ILST',
  'incarnate word': 'UIW',
  'incarnate word cardinals': 'UIW',
  'indiana': 'IU',
  'indiana hoosiers': 'IU',
  'indiana st': 'INST',
  'indiana state': 'INST',
  'indiana state sycamores': 'INST',
  'iona': 'IONA',
  'iona gaels': 'IONA',
  'iowa': 'IOWA',
  'iowa hawkeyes': 'IOWA',
  'iowa state': 'ISU',
  'iowa state cyclones': 'ISU',
  'iu indianapolis': 'IUIN',
  'iu indianapolis jaguars': 'IUIN',
  'iu indy': 'IUIN',
  'jackson st': 'JKST',
  'jackson state': 'JKST',
  'jackson state tigers': 'JKST',
  'jacksonville': 'JAX',
  'jacksonville dolphins': 'JAX',
  'jacksonville state': 'JXST',
  'jacksonville state gamecocks': 'JXST',
  'james madison': 'JMU',
  'james madison dukes': 'JMU',
  'jax state': 'JXST',
  'kansas': 'KU',
  'kansas city': 'KC',
  'kansas city roos': 'KC',
  'kansas jayhawks': 'KU',
  'kansas st': 'KSU',
  'kansas state': 'KSU',
  'kansas state wildcats': 'KSU',
  'kennesaw st': 'KENN',
  'kennesaw state': 'KENN',
  'kennesaw state owls': 'KENN',
  'kent state': 'KENT',
  'kent state golden': 'KENT',
  'kent state golden flashes': 'KENT',
  'kentucky': 'UK',
  'kentucky wildcats': 'UK',
  'la salle': 'LAS',
  'la salle explorers': 'LAS',
  'lafayette': 'LAF',
  'lafayette leopards': 'LAF',
  'lamar': 'LAM',
  'lamar cardinals': 'LAM',
  'le moyne': 'LEM',
  'le moyne dolphins': 'LEM',
  'lehigh': 'LEH',
  'lehigh mountain': 'LEH',
  'lehigh mountain hawks': 'LEH',
  'liberty': 'LIB',
  'liberty flames': 'LIB',
  'lindenwood': 'LIN',
  'lindenwood lions': 'LIN',
  'lipscomb': 'LIP',
  'lipscomb bisons': 'LIP',
  'little rock': 'LR',
  'little rock trojans': 'LR',
  'lmu': 'LMU',
  'long beach st': 'LBSU',
  'long beach state': 'LBSU',
  'long beach state beach': 'LBSU',
  'long island': 'LIU',
  'long island university': 'LIU',
  'long island university sharks': 'LIU',
  'longwood': 'LONG',
  'longwood lancers': 'LONG',
  'louisiana': 'UL',
  'louisiana ragin\'': 'UL',
  'louisiana ragin\' cajuns': 'UL',
  'louisiana tech': 'LT',
  'louisiana tech bulldogs': 'LT',
  'louisville': 'LOU',
  'louisville cardinals': 'LOU',
  'loyola chicago': 'LUC',
  'loyola chicago ramblers': 'LUC',
  'loyola maryland': 'L-MD',
  'loyola maryland greyhounds': 'L-MD',
  'loyola marymount': 'LMU',
  'loyola marymount lions': 'LMU',
  'loyola md': 'L-MD',
  'lsu': 'LSU',
  'lsu tigers': 'LSU',
  'maine': 'ME',
  'maine black': 'ME',
  'maine black bears': 'ME',
  'manhattan': 'MAN',
  'manhattan jaspers': 'MAN',
  'marist': 'MRST',
  'marist red': 'MRST',
  'marist red foxes': 'MRST',
  'marquette': 'MARQ',
  'marquette golden': 'MARQ',
  'marquette golden eagles': 'MARQ',
  'marshall': 'MRSH',
  'marshall thundering': 'MRSH',
  'marshall thundering herd': 'MRSH',
  'maryland': 'MD',
  'maryland eastern shore': 'UMES',
  'maryland eastern shore hawks': 'UMES',
  'maryland terrapins': 'MD',
  'massachusetts': 'MASS',
  'massachusetts minutemen': 'MASS',
  'mcneese': 'MCN',
  'mcneese cowboys': 'MCN',
  'md eastern': 'UMES',
  'memphis': 'MEM',
  'memphis tigers': 'MEM',
  'mercer': 'MER',
  'mercer bears': 'MER',
  'mercyhurst': 'MERC',
  'mercyhurst lakers': 'MERC',
  'merrimack': 'MRMK',
  'merrimack warriors': 'MRMK',
  'miami': 'MIA',
  'miami hurricanes': 'MIA',
  'miami oh': 'M-OH',
  'miami oh redhawks': 'M-OH',
  'michigan': 'MICH',
  'michigan st': 'MSU',
  'michigan state': 'MSU',
  'michigan state spartans': 'MSU',
  'michigan wolverines': 'MICH',
  'middle tennessee blue': 'MTSU',
  'middle tennessee blue raiders': 'MTSU',
  'milwaukee': 'MILW',
  'milwaukee panthers': 'MILW',
  'minnesota': 'MINN',
  'minnesota golden': 'MINN',
  'minnesota golden gophers': 'MINN',
  'miss valley st': 'MVSU',
  'mississippi st': 'MSST',
  'mississippi state': 'MSST',
  'mississippi state bulldogs': 'MSST',
  'mississippi valley state delta': 'MVSU',
  'mississippi valley state delta devils': 'MVSU',
  'missouri': 'MIZ',
  'missouri st': 'MOST',
  'missouri state': 'MOST',
  'missouri state bears': 'MOST',
  'missouri tigers': 'MIZ',
  'monmouth': 'MONM',
  'monmouth hawks': 'MONM',
  'montana': 'MONT',
  'montana grizzlies': 'MONT',
  'montana st': 'MTST',
  'montana state': 'MTST',
  'montana state bobcats': 'MTST',
  'morehead st': 'MORE',
  'morehead state': 'MORE',
  'morehead state eagles': 'MORE',
  'morgan st': 'MORG',
  'morgan state': 'MORG',
  'morgan state bears': 'MORG',
  'mount st mary\'s': 'MSM',
  'mount st mary\'s mountaineers': 'MSM',
  'mount st marys': 'MSM',
  'mtsu': 'MTSU',
  'murray st': 'MUR',
  'murray state': 'MUR',
  'murray state racers': 'MUR',
  'n arizona': 'NAU',
  'n colorado': 'UNCO',
  'n dakota st': 'NDSU',
  'n illinois': 'NIU',
  'n kentucky': 'NKU',
  'n\'western st': 'NWST',
  'navy': 'NAVY',
  'navy midshipmen': 'NAVY',
  'nc a and t': 'NCAT',
  'nc central': 'NCCU',
  'nc state': 'NCSU',
  'nc state wolfpack': 'NCSU',
  'nebraska': 'NEB',
  'nebraska cornhuskers': 'NEB',
  'nevada': 'NEV',
  'nevada wolf': 'NEV',
  'nevada wolf pack': 'NEV',
  'new hampshire': 'UNH',
  'new hampshire wildcats': 'UNH',
  'new haven': 'NHVN',
  'new haven chargers': 'NHVN',
  'new mexico': 'UNM',
  'new mexico lobos': 'UNM',
  'new mexico st': 'NMSU',
  'new mexico state': 'NMSU',
  'new mexico state aggies': 'NMSU',
  'new orleans': 'UNO',
  'new orleans privateers': 'UNO',
  'niagara': 'NIA',
  'niagara purple': 'NIA',
  'niagara purple eagles': 'NIA',
  'nicholls': 'NICH',
  'nicholls colonels': 'NICH',
  'njit': 'NJIT',
  'njit highlanders': 'NJIT',
  'norfolk st': 'NORF',
  'norfolk state': 'NORF',
  'norfolk state spartans': 'NORF',
  'north alabama': 'UNA',
  'north alabama lions': 'UNA',
  'north carolina': 'UNC',
  'north carolina a and t': 'NCAT',
  'north carolina a and t aggies': 'NCAT',
  'north carolina central': 'NCCU',
  'north carolina central eagles': 'NCCU',
  'north carolina tar': 'UNC',
  'north carolina tar heels': 'UNC',
  'north dakota': 'UND',
  'north dakota fighting': 'UND',
  'north dakota fighting hawks': 'UND',
  'north dakota state': 'NDSU',
  'north dakota state bison': 'NDSU',
  'north florida': 'UNF',
  'north florida ospreys': 'UNF',
  'north texas': 'UNT',
  'north texas mean': 'UNT',
  'north texas mean green': 'UNT',
  'northeastern': 'NE',
  'northeastern huskies': 'NE',
  'northern arizona': 'NAU',
  'northern arizona lumberjacks': 'NAU',
  'northern colorado': 'UNCO',
  'northern colorado bears': 'UNCO',
  'northern illinois': 'NIU',
  'northern illinois huskies': 'NIU',
  'northern iowa': 'UNI',
  'northern iowa panthers': 'UNI',
  'northern kentucky': 'NKU',
  'northern kentucky norse': 'NKU',
  'northwestern': 'NU',
  'northwestern state': 'NWST',
  'northwestern state demons': 'NWST',
  'northwestern wildcats': 'NU',
  'notre dame': 'ND',
  'notre dame fighting': 'ND',
  'notre dame fighting irish': 'ND',
  'oakland': 'OAK',
  'oakland golden': 'OAK',
  'oakland golden grizzlies': 'OAK',
  'ohio': 'OHIO',
  'ohio bobcats': 'OHIO',
  'ohio state': 'OSU',
  'ohio state buckeyes': 'OSU',
  'oklahoma': 'OU',
  'oklahoma sooners': 'OU',
  'oklahoma st': 'OKST',
  'oklahoma state': 'OKST',
  'oklahoma state cowboys': 'OKST',
  'old dominion': 'ODU',
  'old dominion monarchs': 'ODU',
  'ole miss': 'MISS',
  'ole miss rebels': 'MISS',
  'omaha': 'OMA',
  'omaha mavericks': 'OMA',
  'oral roberts': 'ORU',
  'oral roberts golden': 'ORU',
  'oral roberts golden eagles': 'ORU',
  'oregon': 'ORE',
  'oregon ducks': 'ORE',
  'oregon st': 'ORST',
  'oregon state': 'ORST',
  'oregon state beavers': 'ORST',
  'pacific': 'PAC',
  'pacific tigers': 'PAC',
  'penn': 'PENN',
  'penn state': 'PSU',
  'penn state nittany': 'PSU',
  'penn state nittany lions': 'PSU',
  'pennsylvania': 'PENN',
  'pennsylvania quakers': 'PENN',
  'pepperdine': 'PEPP',
  'pepperdine waves': 'PEPP',
  'pitt': 'PITT',
  'pittsburgh': 'PITT',
  'pittsburgh panthers': 'PITT',
  'portland': 'PORT',
  'portland pilots': 'PORT',
  'portland st': 'PRST',
  'portland state': 'PRST',
  'portland state vikings': 'PRST',
  'prairie view': 'PV',
  'prairie view a and m': 'PV',
  'prairie view a and m panthers': 'PV',
  'presbyterian': 'PRES',
  'presbyterian blue': 'PRES',
  'presbyterian blue hose': 'PRES',
  'princeton': 'PRIN',
  'princeton tigers': 'PRIN',
  'providence': 'PROV',
  'providence friars': 'PROV',
  'purdue': 'PUR',
  'purdue boilermakers': 'PUR',
  'purdue fort wayne': 'PFW',
  'purdue fort wayne mastodons': 'PFW',
  'purdue fw': 'PFW',
  'queens': 'QUC',
  'queens university': 'QUC',
  'queens university royals': 'QUC',
  'quinnipiac': 'QUIN',
  'quinnipiac bobcats': 'QUIN',
  'radford': 'RAD',
  'radford highlanders': 'RAD',
  'rhode island': 'URI',
  'rhode island rams': 'URI',
  'rice': 'RICE',
  'rice owls': 'RICE',
  'richmond': 'RICH',
  'richmond spiders': 'RICH',
  'rider': 'RID',
  'rider broncs': 'RID',
  'robert morris': 'RMU',
  'robert morris colonials': 'RMU',
  'rutgers': 'RUTG',
  'rutgers scarlet': 'RUTG',
  'rutgers scarlet knights': 'RUTG',
  's dakota st': 'SDST',
  's illinois': 'SIU',
  'sacramento st': 'SAC',
  'sacramento state': 'SAC',
  'sacramento state hornets': 'SAC',
  'sacred heart': 'SHU',
  'sacred heart pioneers': 'SHU',
  'saint francis': 'SFPA',
  'saint francis red': 'SFPA',
  'saint francis red flash': 'SFPA',
  'saint joseph\'s': 'JOES',
  'saint joseph\'s hawks': 'JOES',
  'saint louis': 'SLU',
  'saint louis billikens': 'SLU',
  'saint mary\'s': 'SMC',
  'saint mary\'s gaels': 'SMC',
  'saint peter\'s': 'SPU',
  'saint peter\'s peacocks': 'SPU',
  'sam houston': 'SHSU',
  'sam houston bearkats': 'SHSU',
  'samford': 'SAM',
  'samford bulldogs': 'SAM',
  'san diego': 'USD',
  'san diego st': 'SDSU',
  'san diego state': 'SDSU',
  'san diego state aztecs': 'SDSU',
  'san diego toreros': 'USD',
  'san francisco': 'SF',
  'san francisco dons': 'SF',
  'san jos st': 'SJSU',
  'san jos state': 'SJSU',
  'san jos state spartans': 'SJSU',
  'santa barbara': 'UCSB',
  'santa clara': 'SCU',
  'santa clara broncos': 'SCU',
  'sc state': 'SCST',
  'sc upstate': 'UPST',
  'se louisiana': 'SELA',
  'se louisiana lions': 'SELA',
  'se missouri': 'SEMO',
  'seattle u': 'SEA',
  'seattle u redhawks': 'SEA',
  'seton hall': 'HALL',
  'seton hall pirates': 'HALL',
  'sf austin': 'SFA',
  'siena': 'SIE',
  'siena saints': 'SIE',
  'siu edwardsville': 'SIUE',
  'siu edwardsville cougars': 'SIUE',
  'siue': 'SIUE',
  'smu': 'SMU',
  'smu mustangs': 'SMU',
  'so indiana': 'USI',
  'south alabama': 'USA',
  'south alabama jaguars': 'USA',
  'south carolina': 'SC',
  'south carolina gamecocks': 'SC',
  'south carolina state': 'SCST',
  'south carolina state bulldogs': 'SCST',
  'south carolina upstate': 'UPST',
  'south carolina upstate spartans': 'UPST',
  'south dakota': 'SDAK',
  'south dakota coyotes': 'SDAK',
  'south dakota state': 'SDST',
  'south dakota state jackrabbits': 'SDST',
  'south florida': 'USF',
  'south florida bulls': 'USF',
  'southeast missouri state': 'SEMO',
  'southeast missouri state redhawks': 'SEMO',
  'southern': 'SOU',
  'southern illinois': 'SIU',
  'southern illinois salukis': 'SIU',
  'southern indiana screaming': 'USI',
  'southern indiana screaming eagles': 'USI',
  'southern jaguars': 'SOU',
  'southern miss': 'USM',
  'southern miss golden': 'USM',
  'southern miss golden eagles': 'USM',
  'southern utah': 'SUU',
  'southern utah thunderbirds': 'SUU',
  'st bonaventure': 'SBU',
  'st bonaventure bonnies': 'SBU',
  'st john\'s': 'SJU',
  'st john\'s red': 'SJU',
  'st john\'s red storm': 'SJU',
  'st thomas minnesota': 'STMN',
  'st thomas minnesota tommies': 'STMN',
  'st thomas mn': 'STMN',
  'stanford': 'STAN',
  'stanford cardinal': 'STAN',
  'stephen f austin': 'SFA',
  'stephen f austin lumberjacks': 'SFA',
  'stetson': 'STET',
  'stetson hatters': 'STET',
  'stonehill': 'STO',
  'stonehill skyhawks': 'STO',
  'stony brook': 'STBK',
  'stony brook seawolves': 'STBK',
  'syracuse': 'SYR',
  'syracuse orange': 'SYR',
  'tarleton st': 'TAR',
  'tarleton state': 'TAR',
  'tarleton state texans': 'TAR',
  'tcu': 'TCU',
  'tcu horned': 'TCU',
  'tcu horned frogs': 'TCU',
  'temple': 'TEM',
  'temple owls': 'TEM',
  'tennessee': 'TENN',
  'tennessee st': 'TNST',
  'tennessee state': 'TNST',
  'tennessee state tigers': 'TNST',
  'tennessee tech': 'TNTC',
  'tennessee tech golden': 'TNTC',
  'tennessee tech golden eagles': 'TNTC',
  'tennessee volunteers': 'TENN',
  'texas': 'TEX',
  'texas a and m': 'TA&M',
  'texas a and m aggies': 'TA&M',
  'texas a and m cc': 'AMCC',
  'texas a and m corpus christi': 'AMCC',
  'texas a and m corpus christi islanders': 'AMCC',
  'texas longhorns': 'TEX',
  'texas southern': 'TXSO',
  'texas southern tigers': 'TXSO',
  'texas st': 'TXST',
  'texas state': 'TXST',
  'texas state bobcats': 'TXST',
  'texas tech': 'TTU',
  'texas tech red': 'TTU',
  'texas tech red raiders': 'TTU',
  'the citadel': 'CIT',
  'the citadel bulldogs': 'CIT',
  'toledo': 'TOL',
  'toledo rockets': 'TOL',
  'towson': 'TOW',
  'towson tigers': 'TOW',
  'troy': 'TROY',
  'troy trojans': 'TROY',
  'tulane': 'TULN',
  'tulane green': 'TULN',
  'tulane green wave': 'TULN',
  'tulsa': 'TLSA',
  'tulsa golden': 'TLSA',
  'tulsa golden hurricane': 'TLSA',
  'uab': 'UAB',
  'uab blazers': 'UAB',
  'ualbany': 'UALB',
  'ualbany great': 'UALB',
  'ualbany great danes': 'UALB',
  'uc davis': 'UCD',
  'uc davis aggies': 'UCD',
  'uc irvine': 'UCI',
  'uc irvine anteaters': 'UCI',
  'uc riverside': 'UCR',
  'uc riverside highlanders': 'UCR',
  'uc san diego': 'UCSD',
  'uc san diego tritons': 'UCSD',
  'uc santa barbara': 'UCSB',
  'uc santa barbara gauchos': 'UCSB',
  'ucf': 'UCF',
  'ucf knights': 'UCF',
  'ucla': 'UCLA',
  'ucla bruins': 'UCLA',
  'uconn': 'CONN',
  'uconn huskies': 'CONN',
  'uic': 'UIC',
  'uic flames': 'UIC',
  'ul monroe': 'ULM',
  'ul monroe warhawks': 'ULM',
  'umass': 'MASS',
  'umass lowell': 'UML',
  'umass lowell river': 'UML',
  'umass lowell river hawks': 'UML',
  'umbc': 'UMBC',
  'umbc retrievers': 'UMBC',
  'unc asheville': 'UNCA',
  'unc asheville bulldogs': 'UNCA',
  'unc greensboro': 'UNCG',
  'unc greensboro spartans': 'UNCG',
  'unc wilmington': 'UNCW',
  'unc wilmington seahawks': 'UNCW',
  'unlv': 'UNLV',
  'unlv rebels': 'UNLV',
  'usc': 'USC',
  'usc trojans': 'USC',
  'ut arlington': 'UTA',
  'ut arlington mavericks': 'UTA',
  'ut martin': 'UTM',
  'ut martin skyhawks': 'UTM',
  'ut rio grande': 'RGV',
  'ut rio grande valley': 'RGV',
  'ut rio grande valley vaqueros': 'RGV',
  'utah': 'UTAH',
  'utah state': 'USU',
  'utah state aggies': 'USU',
  'utah tech': 'UTU',
  'utah tech trailblazers': 'UTU',
  'utah utes': 'UTAH',
  'utah valley': 'UVU',
  'utah valley wolverines': 'UVU',
  'utep': 'UTEP',
  'utep miners': 'UTEP',
  'utsa': 'UTSA',
  'utsa roadrunners': 'UTSA',
  'valparaiso': 'VAL',
  'valparaiso beacons': 'VAL',
  'vanderbilt': 'VAN',
  'vanderbilt commodores': 'VAN',
  'vcu': 'VCU',
  'vcu rams': 'VCU',
  'vermont': 'UVM',
  'vermont catamounts': 'UVM',
  'villanova': 'VILL',
  'villanova wildcats': 'VILL',
  'virginia': 'UVA',
  'virginia cavaliers': 'UVA',
  'virginia tech': 'VT',
  'virginia tech hokies': 'VT',
  'vmi': 'VMI',
  'vmi keydets': 'VMI',
  'w carolina': 'WCU',
  'w illinois': 'WIU',
  'w michigan': 'WMU',
  'wagner': 'WAG',
  'wagner seahawks': 'WAG',
  'wake forest': 'WAKE',
  'wake forest demon': 'WAKE',
  'wake forest demon deacons': 'WAKE',
  'washington': 'WASH',
  'washington huskies': 'WASH',
  'washington st': 'WSU',
  'washington state': 'WSU',
  'washington state cougars': 'WSU',
  'weber st': 'WEB',
  'weber state': 'WEB',
  'weber state wildcats': 'WEB',
  'west georgia': 'WGA',
  'west georgia wolves': 'WGA',
  'west virginia': 'WVU',
  'west virginia mountaineers': 'WVU',
  'western carolina': 'WCU',
  'western carolina catamounts': 'WCU',
  'western illinois': 'WIU',
  'western illinois leathernecks': 'WIU',
  'western kentucky': 'WKU',
  'western kentucky hilltoppers': 'WKU',
  'western ky': 'WKU',
  'western michigan': 'WMU',
  'western michigan broncos': 'WMU',
  'wichita st': 'WICH',
  'wichita state': 'WICH',
  'wichita state shockers': 'WICH',
  'william and mary': 'W&M',
  'william and mary tribe': 'W&M',
  'winthrop': 'WIN',
  'winthrop eagles': 'WIN',
  'wisconsin': 'WIS',
  'wisconsin badgers': 'WIS',
  'wofford': 'WOF',
  'wofford terriers': 'WOF',
  'wright st': 'WRST',
  'wright state': 'WRST',
  'wright state raiders': 'WRST',
  'wyoming': 'WYO',
  'wyoming cowboys': 'WYO',
  'xavier': 'XAV',
  'xavier musketeers': 'XAV',
  'yale': 'YALE',
  'yale bulldogs': 'YALE',
  'youngstown st': 'YSU',
  'youngstown state': 'YSU',
  'youngstown state penguins': 'YSU',
};
