const FULL_TEAM_NAME_OVERRIDES: Record<string, string> = {
  UConn: "University of Connecticut Huskies",
  "Iowa State": "Iowa State University Cyclones",
  Illinois: "University of Illinois Fighting Illini",
  Auburn: "Auburn University Tigers",
  "San Diego State": "San Diego State University Aztecs",
  BYU: "Brigham Young University Cougars",
  "Washington State": "Washington State University Cougars",
  "Florida Atlantic": "Florida Atlantic University Owls",
  Northwestern: "Northwestern University Wildcats",
  Drake: "Drake University Bulldogs",
  Duquesne: "Duquesne University Dukes",
  UAB: "University of Alabama at Birmingham Blazers",
  Yale: "Yale University Bulldogs",
  "Morehead State": "Morehead State University Eagles",
  "South Dakota State": "South Dakota State University Jackrabbits",
  Stetson: "Stetson University Hatters",
  "North Carolina": "University of North Carolina Tar Heels",
  Arizona: "University of Arizona Wildcats",
  Baylor: "Baylor University Bears",
  Alabama: "University of Alabama Crimson Tide",
  "Saint Mary's": "Saint Mary's College Gaels",
  Clemson: "Clemson University Tigers",
  Dayton: "University of Dayton Flyers",
  "Mississippi State": "Mississippi State University Bulldogs",
  "Michigan State": "Michigan State University Spartans",
  Nevada: "University of Nevada Wolf Pack",
  "New Mexico": "University of New Mexico Lobos",
  "Grand Canyon": "Grand Canyon University Lopes",
  Charleston: "College of Charleston Cougars",
  Colgate: "Colgate University Raiders",
  "Long Beach State": "Long Beach State University Beach",
  Wagner: "Wagner College Seahawks",
  Houston: "University of Houston Cougars",
  Marquette: "Marquette University Golden Eagles",
  Kentucky: "University of Kentucky Wildcats",
  Duke: "Duke University Blue Devils",
  Wisconsin: "University of Wisconsin Badgers",
  "Texas Tech": "Texas Tech University Red Raiders",
  Florida: "University of Florida Gators",
  Nebraska: "University of Nebraska Cornhuskers",
  "Texas A&M": "Texas A&M University Aggies",
  Colorado: "University of Colorado Buffaloes",
  "NC State": "North Carolina State University Wolfpack",
  "James Madison": "James Madison University Dukes",
  Vermont: "University of Vermont Catamounts",
  Oakland: "Oakland University Golden Grizzlies",
  "Western Kentucky": "Western Kentucky University Hilltoppers",
  Longwood: "Longwood University Lancers",
  Purdue: "Purdue University Boilermakers",
  Tennessee: "University of Tennessee Volunteers",
  Creighton: "Creighton University Bluejays",
  Kansas: "University of Kansas Jayhawks",
  Gonzaga: "Gonzaga University Bulldogs",
  "South Carolina": "University of South Carolina Gamecocks",
  Texas: "University of Texas Longhorns",
  "Utah State": "Utah State University Aggies",
  TCU: "Texas Christian University Horned Frogs",
  Virginia: "University of Virginia Cavaliers",
  Oregon: "University of Oregon Ducks",
  McNeese: "McNeese State University Cowboys",
  Samford: "Samford University Bulldogs",
  Akron: "University of Akron Zips",
  "Saint Peter's": "Saint Peter's University Peacocks",
  "Montana State": "Montana State University Bobcats",
};

export function fullTeamName(name: string): string {
  return FULL_TEAM_NAME_OVERRIDES[name] ?? `${name} Basketball`;
}
