// Auto-generated by scripts/generate_matchup_predictor.py — do not edit manually
// Run: python scripts/generate_matchup_predictor.py
// This is a stub file. Run the generator script to populate with real predictions.

export const PREDICTOR_TEAMS: ReadonlyArray<{
  id: number;
  name: string;
  conf: string;
}> = [];

export const PREDICTOR_PROBS_B64 = "";

let _cache: Uint16Array | null = null;

function getProbs(): Uint16Array {
  if (!_cache) {
    if (!PREDICTOR_PROBS_B64) {
      _cache = new Uint16Array(0);
      return _cache;
    }
    const bytes = Uint8Array.from(atob(PREDICTOR_PROBS_B64), (c) => c.charCodeAt(0));
    _cache = new Uint16Array(bytes.buffer);
  }
  return _cache;
}

const N = PREDICTOR_TEAMS.length;

export function getMatchupProb(teamAIdx: number, teamBIdx: number, loc: "N" | "H" | "A"): number | null {
  if (N === 0) return null;
  if (teamAIdx === teamBIdx || teamAIdx < 0 || teamBIdx < 0 || teamAIdx >= N || teamBIdx >= N) {
    return null;
  }

  const flipped = teamAIdx > teamBIdx;
  const i = flipped ? teamBIdx : teamAIdx;
  const j = flipped ? teamAIdx : teamBIdx;

  const pairIdx = i * N - Math.floor((i * (i + 1)) / 2) + (j - i - 1);

  let storageLoc: number;
  if (loc === "N") {
    storageLoc = 0;
  } else if ((!flipped && loc === "H") || (flipped && loc === "A")) {
    storageLoc = 1;
  } else {
    storageLoc = 2;
  }

  const raw = getProbs()[pairIdx * 3 + storageLoc] / 65535;
  return flipped ? 1 - raw : raw;
}

export function getTeamIdx(teamId: number): number {
  if (N === 0) return -1;
  let lo = 0;
  let hi = N - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const cmp = PREDICTOR_TEAMS[mid].id - teamId;
    if (cmp === 0) return mid;
    if (cmp < 0) lo = mid + 1;
    else hi = mid - 1;
  }
  return -1;
}
